account/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'account'

urlpatterns = [
    #path('', TemplateView.as_view(template_name='index.html')),
    path('register/options', views.signupoptions,name='signupOptions'),
    path('register/signup_user',views.signup,name='register'),
    path('register/signup_choosen',views.loadTemplate,name='loadTemplate'),
    path('profile/', views.profile, name='profile'),
    path('logout',views.logout,name='logout')
]

sih/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('accident/', include('accident.urls')),
    path('about/',TemplateView.as_view(template_name='about.html')),
    path('api-auth/', include('rest_framework.urls')),
    path('contact/',views.contact,name='contact_goldenhour'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register_as_user/',TemplateView.as_view(template_name='account\signup_next_user.html')),
    path('login/',views.login,name='Login')
]

templates/about.html
{% extends 'base.html' %}
{% block content %}
<html>
    <head>
        <title>About</title>
    </head>
    <body>
        <h1 align='center' style="font-family:Arial, Helvetica, sans-serif;">About</h1>
        <div style="text-align: justify; width: fit-content; background-color: rgba(222, 233, 222, 0.76); border-radius: 10px; box-shadow: 0 0 5px 0 black;">
            <p style=" margin:20px; padding: 20px; font-size:20px;font-family: Arial, Helvetica, sans-serif; word-wrap: normal;">
                This Idea is emerged due to increasing rate of Accidents
                on the roads and the casuality rate is far more than that,
                all because either the person wouldn't get help in the 
               <span style="color:red;">"golden hour"</span> of medication or no one is nearby to help.
                So we have found a all time solution for it, using the 
                developing technology.
                <span style="color:red;">"Accident Alert System"</span>
                Using the GPS that will be installed in the car, the emer-
                gency request will be sent to the respective authorized or
                register authority(eg: Police Station , Hospitals etc) the
                cordinates of the the person Accident location would be send
                on the server of our website where hospitals and police stat-
                ion and help will be send to that person.
            </p>
            <h4 align='center'> &copy Golden Hour Rescue </h4>
        </div>
    </body>
</html>
{% endblock%}

templates/base.html
{% load static %}
<html>
    <head>
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/OpenLayers.js"></script>
      <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      {% block css_content %}
    
      {% endblock %}
      
      <style>
      #social{
        float:right;
      }
      </style>
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen,projection" >
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
 
    </head>

    <body>
        <h1 id="title", align='center' style=" border-radius:5px; width:fit-content; margin:auto; display:block;" >Golden Hour Rescue</h1>
            <div class="topnav">
              <a class="active" href="/"><i class="fa fa-home"></i> Home</a>
              <a href="{% url 'contact_goldenhour' %}"><i class="fa fa-book"></i> Contact</a>
              <a href="/about"><i class="fa fa-history"></i>About</a>
              <a href="{% url 'account:signupOptions'%}"><i class="fa fa-user"></i> Register</a>
              <a href="{% url 'logout' %}"><i class="fa fa-sign-out-alt"></i>Log-Out</a>
              <a href="{% url 'login'%}"><i class="fa fa-sign-in-alt"></i> Log-In</a>
              <a href="#" id="social"><i class="fab fa-facebook-f"></i> </a>
              <a href="#" id="social"><i class="fab fa-instagram"></i> </a>
              <a href="#" id="social"><i class="fab fa-google-plus-g"></i> </a>
            </div>
    {% block content %}

    {% endblock %}
    {% block js_content %}
    
    {% endblock %}
    </body>
</html>

templates/contact_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<html>
        <head>
                <title>Contact</title>
                <style>
                    label{
                        font-size: 20px;
                        font-family: Arial, Helvetica, sans-serif;
                    }
                    .input_fields{
                        position: relative;
                        float: right;
                        padding: 3px;
                        border-radius: 20px;
                        box-shadow: 0 0 2px 0 blue;
                    }
                    div#outerbox{
                        margin: auto;
                        width: fit-content;
                    }
                    div#signup_block{
                        background-color:rgba(148, 247, 242, 0.356);
                        padding: 10px;
                        max-width: fit-content;
                        margin: auto;
                        display: block;
                        margin-bottom: 30px;
                        border-top: solid 2px rgb(102, 92, 90);
                        border-radius: 10px;
                        box-shadow: 0 0 10px 0 whitesmoke;
                        text-shadow:yellowgreen;
                        text-align: center;
                    }
                    .btns{
                        position: relative;
                        text-align: center;
                        padding: 3px;
                        font-size: 20px;
                        font-family: Arial, Helvetica, sans-serif;
                        border-radius: 30px;
                        margin:auto;
                        display: block;
                        background-color: #4CAF50;
                    }
                    .address{
                        height: auto;
                    }
                </style>
                 <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sign-in/">
                 <!-- Bootstrap core CSS -->
                 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            </head>
    <h3 align='center' style="font-family:Arial, Helvetica, sans-serif;"></h3>
    <body>
            <h5 align='center' style="margin:20px;">{{message}}</h4>
        <div id="outerbox" style="background-color: rgba(220, 240, 237, 0.541);">

            <div id="signup_block">
                   
                    <form action="{% url 'contact_goldenhour' %}" method="POST">
                        {% csrf_token %}
                        <h4>Subject:</h4>
                        <input type="text" name="subject" class="form-control input_fields"> 
                        <h4>Please Write Your Query Below:</h4>
                        <div style="margin:auto;display:block; width:fit-content;">
                    <textarea name="query"  cols="40" rows="10" class="form-control input_fields">            </textarea>
                        </div>
                    <br><br>
                    <label align='center'>Your Email Id</label>
                    <input type="Email" name="email" class="form-control input_fields">
                    <br><br>
                    <br>
                    <input type="submit" name="submit" value="Send" class=" btns btn btn-lg btn-primary btn-block">
                    </form>
        

            </div>
        </div>
    </body>    
</html>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<html>
    <head>
        <title>Hompage</title>
        <style>
            body{
                background-image: url("https://images.pexels.com/photos/220996/pexels-photo-220996.jpeg?cs=srgb&dl=accident-action-auto-220996.jpg&fm=jpg")
            }
            div#head{
                margin: auto;
                border-top: solid 3px black;
                display: block;
                background-color: rgba(148, 241, 241, 0.349);
                width: fit-content;
                border-radius:20px;
                box-shadow: 0 0 10px 0 black;
                padding: 10px;
            }
            div#paragraph{
                background-color:rgba(241, 248, 240, 0.596);
                margin: 20px;
                border-radius:10px;
                box-shadow: 0 0 5px 0 black;
                border-top: solid 2px black;
                width: 1000px;
                margin-bottom: 10px;

            }
            img#image{
                width: 800px;
                height: 500px;
                border-radius: 10px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        
    </head>
    <body>
        <h3 align='center' style="background-color:rgba(196, 238, 238, 0.349);">{{message}}</h3>
        <div id="head">
            <div style="margin:auto; display:block; width:fit-content;">
            <img src="{% static 'img\sih2019.png' %}" alt="sih_header" width="1000px" style="border-radius:30px; margin:10px;">
            </div>
            <div id="paragraph">
            <p style="text-align:justify; margin: 20px; font-family: Arial, Helvetica, sans-serif; font-size:20px;">
                This Site is a part of the solution for the problem statement,
                in <span style="color:darkred;">"Smart India Hackthon 2019"</span> to solve the accidents issue
                raging day by day in India , making use of the technologies
                and GPS system.
            </p>
        </div>
        </div>
        <br>
        <br>
        <div style="margin:auto; width:fit-content; display:block; padding: 20px; border-radius:20px; box-shadow: 0 0 10px 0 aqua; border-top: solid 2px black; background-color: rgba(148, 241, 241, 0.349)">
            <div style="margin:auto; width:fit-content; display:block;">
                <img class="mySlides" src="{% static 'img/img1.png' %}"  id="image">
        <img class="mySlides" src="{% static 'img/img2.png' %}"   id="image">
        <img class="mySlides" src="{% static 'img/img3.png' %}"   id="image">
        <img class="mySlides" src="{% static 'img/img4.png' %}"   id="image">
            </div>
    </div>   
</body>
</html>
<script src="{% static 'js/base.js' %}"></script>
{% endblock %}

templates/userloginbasefile.html
{% load static %}
<html>
    <head>
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/OpenLayers.js"></script>
      <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      {% block css_content %}
    
      {% endblock %}
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen,projection" >
    </head>

    <body>
        <h1 id="title", align='center' style=" border-radius:5px; width:fit-content; margin:auto; display:block;" >Golden Hour Rescue</h1>
            <div class="topnav">
              <a class="active" href="#"><i class="fa fa-home"></i> Profile</a>
              <a href="#"><i class="fa fa-book"></i>Location</a>
              <a href="#"><i class="fa fa-file"></i> Report</a>
              <a href="{% url 'account:logout' %}"><i class="fa fa-sign-out-alt"></i>Log-Out</a>
            </div>
    {% block content %}

    {% endblock %}
    {% block js_content %}
    
    {% endblock %}
    </body>
</html>